set -g default-terminal "tmux-256color"
set -s escape-time 0
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on
set -g mouse on

# vi key movement for copy/pasta mode
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind Space copy-mode

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r Left resize-pane -L 5
bind -r Right resize-pane -R 5
bind -r Up resize-pane -U 5
bind -r Down resize-pane -D 5


unbind r
bind r source-file ~/.tmux.conf

unbind w
unbind s
bind s display-popup -E -x C -y C -w 60% -h 45% 'sh -c "$HOME/dotfiles/tmux/scripts/session-picker.sh"'

unbind C-b
set-option -g prefix C-s

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'o0th/tmux-nova'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @nova-nerdfonts true
set -g @nova-nerdfonts-left 
set -g @nova-nerdfonts-right 

set -g @nova-pane-active-border-style "#539bf5"
set -g @nova-pane-border-style "#444c56"
set -g @nova-status-style-bg "#2d333b"
set -g @nova-status-style-fg "#adbac7"
set -g @nova-status-style-active-bg "#539bf5"
set -g @nova-status-style-active-fg "#22272e"
set -g @nova-status-style-double-bg "#22272e"

set -g @nova-pane "#I#{?pane_in_mode,  #{pane_mode},}  #W"

set -g @nova-segment-mode "#{?client_prefix,*,▷}"
set -g @nova-segment-mode-colors "#539bf5 #2d333b"

set -g @nova-segment-whoami "#(whoami)@#h"
set -g @nova-segment-whoami-colors "#539bf5 #2d333b"
set -g @nova-segments-0-right "whoami"

set -g @nova-rows 0
set -g @nova-segments-0-left "mode"

run '~/.tmux/plugins/tpm/tpm'

# Pi
set -g extended-keys on
set -g extended-keys-format csi-u


bind [ split-window -h -c "#{pane_current_path}"
bind ] split-window -v -c "#{pane_current_path}"

set -ga terminal-features ",*:progressbar" # Show progress bar at bottom
